name: Release

on:
  release:
    types: [created]


jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: '.nvmrc'
          registry-url: https://npm.pkg.github.com/


      - name: Install
        run: pnpm install

      - name: Typecheck
        run: pnpm run type-check

      - run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
