name: Test

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: '.nvmrc'


      - name: Install
        run: pnpm install

      - name: Typecheck
        run: pnpm run type-check

      - name: Build
        run: pnpm build

      - name: Install tinyproxy
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install tinyproxy
      - name: Test
        env:
          OPENAI_URL: ${{ secrets.OPENAI_URL }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        run: |
          pnpm test
